# This is a basic workflow to help you get started with Actions
name: CI
# целевые события для запуска
# в данном случае это push и pull_request, в ветку main
on:
  push:
    branches: [ main ]
# выполняемые действия
jobs:
  run_program:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        
      - name: install software
        run: sudo apt-get install -y chromium-browser      
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run UI-tests  
        run: pytest UITest.py
